spring.application.name=backend

# H2 Database configuration in File Mode
spring.datasource.url=jdbc:h2:file:./data/leaks_survey
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Jackson date format (accepte "2026-07-09 13:59" et "2026-07-09T10:20:27.263681")
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSSSS
spring.jackson.time-zone=Africa/Casablanca

# Server configuration
server.address=0.0.0.0
server.port=8080

# File upload configuration
file.upload-dir=uploads/photos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

# JWT Configuration
jwtSecretKey=LeaksSurvey2024SecretKeyForJWTTokenGenerationMustBeLongEnough256Bits!!
jwt.access.duration=3600000
jwt.refresh.duration=604800000
